import OpenAI from "openai";

export function createOpenAIClient() {
  if (!process.env.OPENAI_API_KEY) {
    return null;
  }

  return new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });
}

export async function generateCompassionateRewrite(input: string) {
  const client = createOpenAIClient();

  if (!client) {
    return {
      rewrite:
        "I want to understand what felt painful for you. Can we pause, breathe, and try again with care?",
      note: "OPENAI_API_KEY is not configured, so Lux returned a local fallback.",
    };
  }

  const response = await client.responses.create({
    model: "gpt-4.1-mini",
    input: [
      {
        role: "system",
        content:
          "You are SophIA inside Lux Aeterna. Rewrite conflict language into emotionally safe, accountable, compassionate communication.",
      },
      {
        role: "user",
        content: input,
      },
    ],
  });

  return {
    rewrite: response.output_text,
    note: "Generated by SophIA mediation protocol.",
  };
}
