"use client";

import { AlertTriangle, CheckCircle2, Copy, Heart, Pause, RefreshCw, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { GlassCard } from "@/components/ui/glass-card";
import { Button } from "@/components/ui/button";

const sample =
  "You never listen to me. I am tired of repeating myself and feeling like I do not matter.";

function analyzeConflict(text: string) {
  const lowered = text.toLowerCase();
  return [
    {
      label: "Toxic generalization",
      active: lowered.includes("never") || lowered.includes("always"),
      suggestion: "Replace absolutes with a specific moment and the impact it had.",
    },
    {
      label: "Defensiveness risk",
      active: lowered.includes("you "),
      suggestion: "Lead with an inner feeling before naming the behavior.",
    },
    {
      label: "Repair opportunity",
      active: text.length > 20,
      suggestion: "Add one sentence of care before the request.",
    },
  ];
}

export function ConflictAnalyzer() {
  const [text, setText] = useState(sample);
  const [rewrite, setRewrite] = useState(
    "I feel scared and unseen when I repeat something important. Could we slow down and reflect back what each of us heard?",
  );
  const [note, setNote] = useState("Local SophIA safety draft.");
  const [isLoading, setIsLoading] = useState(false);
  const [isBreathing, setIsBreathing] = useState(false);
  const [error, setError] = useState("");
  const [copyStatus, setCopyStatus] = useState("");
  const signals = useMemo(() => analyzeConflict(text), [text]);
  const activeSignalCount = signals.filter((signal) => signal.active).length;

  async function requestRewrite() {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/mediator/rewrite", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      const payload = (await response.json()) as { rewrite?: string; note?: string; error?: string };

      if (!response.ok) {
        throw new Error(payload.error ?? "SophIA could not complete the rewrite.");
      }

      setRewrite(payload.rewrite ?? rewrite);
      setNote(payload.note ?? "Generated by SophIA mediation protocol.");
    } catch (caughtError) {
      setError(caughtError instanceof Error ? caughtError.message : "Unexpected mediation error.");
    } finally {
      setIsLoading(false);
    }
  }

  async function copyRewrite() {
    try {
      await navigator.clipboard.writeText(rewrite);
      setCopyStatus("Copied to clipboard");
    } catch {
      setCopyStatus("Copy unavailable in this browser");
    }
    window.setTimeout(() => setCopyStatus(""), 1800);
  }

  return (
    <GlassCard luminous>
      <div className="grid gap-8 lg:grid-cols-[1fr_.85fr]">
        <div>
          <p className="font-accent text-xs tracking-[0.28em] text-solar-gold">AI CONFLICT MEDIATOR</p>
          <h1 className="mt-3 font-display text-5xl text-white">Slow the spiral before it becomes a wound.</h1>
          <label className="mt-8 block text-sm font-medium text-ivory-light/70" htmlFor="conflict-input">
            Conversation fragment
          </label>
          <textarea
            id="conflict-input"
            value={text}
            onChange={(event) => setText(event.target.value)}
            className="mt-3 min-h-48 w-full rounded-[8px] border border-white/12 bg-deep-space/70 p-4 text-base leading-7 text-ivory-light outline-none transition focus:border-solar-gold/70"
          />
          <div className="mt-4 flex flex-wrap gap-3">
            <Button variant="gold" onClick={requestRewrite} disabled={isLoading || text.trim().length < 3}>
              {isLoading ? (
                <RefreshCw className="h-4 w-4 animate-spin" aria-hidden="true" />
              ) : (
                <WandSparkles className="h-4 w-4" aria-hidden="true" />
              )}
              {isLoading ? "Listening..." : "Compassionate rewrite"}
            </Button>
            <Button variant="ghost" onClick={() => setIsBreathing((current) => !current)}>
              <Pause className="h-4 w-4" aria-hidden="true" />
              {isBreathing ? "End breath pause" : "Start breath pause"}
            </Button>
          </div>
          {error ? (
            <p className="mt-4 rounded-[8px] border border-rose-empathy/25 bg-rose-empathy/10 p-3 text-sm text-rose-empathy">
              {error}
            </p>
          ) : null}
          {isBreathing ? (
            <div className="mt-5 rounded-[8px] border border-aura-blue/20 bg-aura-blue/10 p-5">
              <div className="mx-auto grid h-32 w-32 animate-breathe place-items-center rounded-full border border-aura-blue/40 bg-aura-blue/10">
                <span className="text-sm font-semibold text-white">4 in / 6 out</span>
              </div>
              <p className="mt-4 text-center text-sm text-ivory-light/62">
                Pause the reply. Let the body come back online first.
              </p>
            </div>
          ) : null}
        </div>
        <div className="space-y-4">
          <div className="rounded-[8px] border border-harmony-green/20 bg-harmony-green/10 p-5">
            <div className="flex items-center gap-3 text-harmony-green">
              <Heart className="h-5 w-5" aria-hidden="true" />
              <p className="font-semibold">Suggested rewrite</p>
            </div>
            <p className="mt-4 text-sm leading-7 text-ivory-light/72">
              {rewrite}
            </p>
            <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
              <p className="text-xs text-harmony-green/78">{copyStatus || note}</p>
              <Button variant="ghost" onClick={copyRewrite}>
                <Copy className="h-4 w-4" aria-hidden="true" />
                Copy
              </Button>
            </div>
          </div>
          <div className="rounded-[8px] border border-white/10 bg-white/[0.04] p-4">
            <div className="flex items-center justify-between">
              <p className="font-medium text-white">Safety reading</p>
              <span className="rounded-[8px] bg-deep-space px-3 py-1 text-xs text-ivory-light/62">
                {activeSignalCount} active signals
              </span>
            </div>
            <div className="mt-4 h-2 rounded-full bg-white/10">
              <div
                className="h-full rounded-full bg-gradient-to-r from-harmony-green via-solar-gold to-rose-empathy"
                style={{ width: `${Math.min(100, 34 + activeSignalCount * 22)}%` }}
              />
            </div>
          </div>
          {signals.map((signal) => (
            <div
              key={signal.label}
              className="rounded-[8px] border border-white/10 bg-white/[0.04] p-4"
            >
              <div className="flex items-center gap-3">
                {signal.active ? (
                  <AlertTriangle className="h-4 w-4 text-solar-gold" aria-hidden="true" />
                ) : (
                  <CheckCircle2 className="h-4 w-4 text-harmony-green" aria-hidden="true" />
                )}
                <p className="font-medium text-white">{signal.label}</p>
              </div>
              <p className="mt-2 text-sm leading-6 text-ivory-light/58">{signal.suggestion}</p>
            </div>
          ))}
        </div>
      </div>
    </GlassCard>
  );
}
